# Generated by Django 3.2.7 on 2021-10-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['result_at'], 'verbose_name_plural': 'Messages'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='result_at',
        ),
        migrations.AddField(
            model_name='message',
            name='result',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
