# Generated by Django 3.2.7 on 2021-10-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20211025_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='ticket',
            new_name='ticker',
        ),
    ]
